
📖[プロを目指す人のためのRuby入門［改訂2版］ 言語仕様からテスト駆動開発・デバッグ技法まで](https://gihyo.jp/book/2021/978-4-297-12437-3)

#### モジュールに関する高度な話題（つづき）

- 有効範囲を限定できるrefinements  
  refinementsという機能を使うと、独自の変更の有効範囲を限定することができる。  
  この機能で有効範囲を限定しておけば、広範囲に使われるクラスを独自に変更して予期せぬ不具合に遭遇するリスクを減らしてくれる。  
  モジュール内で`refine`メソッドを使ってrefinementsを適用するクラスを指定して、ブロック内にメソッドを書く。
  `using`というメソッドを使うと、refinementsを有効にできる。  
  `using モジュール名`のような書き方でrefinementsを有効化する。`using`でrefinementsを有効化したクラス内でのみ、指定したモジュール内のメソッドが使える。  
  ```ruby
  module SampleModule
    refine String do
      # Stringクラスに対する変更
      # メソッドを定義する
    end
  end

  class SampleClass
  # refinementsを有効化
    using SampleModule

    # このクラス内でのみ、SampleModuleのrefineで定義したメソッドが使える。

  end
  ```

9章。例外処理について。ハンズオンは正規表現チェッカープログラム。

#### 例外の補足  

- 発生した例外を補足しない場合  
  rubyでは例外も例外クラスのインスタンス（例外オブジェクト）担っている。（TypeErrorとかが発生した例外のクラス名）。  
  とくに例外処理をしていないときでも、irbであれば続けて他のコードを動かせるが、rubyコマンドで実行した場合は例外が発生した時点でプログラムが終了する。  

- 例外を補足して処理を続行する場合  
  例外が発生してもプログラムを続行したいときは、例外処理を明示的に書くことでプログラムを続行させられる。  
  ```ruby  
  begin
    # 例外が起きうる処理
  rescue
    # 例外が発生した時の処理
  end
  ```

- 例外処理の流れ  
  例外が発生する場所が明らかであれば、その個所を`begin～rescue`で囲んで例外を補足することができるが、実際のプログラムでは予期できない箇所で例外が発生することもある。  
  例外が発生した個所が`begin~rescue`で囲まれていない場合、例外が発生すると、そこで処理を中断してメソッドの呼び出しを一つづつ戻っていく。  
  メソッド呼び出しを戻る途中にその例外を補足するコードがあれば、そこから処理を続行できる。  
  例外が補足されなければ、発生した例外はメソッド呼び出しを全部さかのぼっても完全に無視されるので、プログラム全体が異常終了する。  

- 例外オブジェクトから情報を取得する  
  例外オブジェクトのメソッドを呼び出すことで、発生した例外に関する情報を取得できる。  
  `message`メソッドは例外発生時のエラーメッセージを返してくれる。  
  `backtrace`メソッドはバックトレース情報（メソッド呼び出しの履歴）を配列にして返してくれる。  
  ```ruby
  begin
    # 例外が起きうる処理
  rescue => 例外オブジェクトを格納する変数
    # 例外が発生した場合の処理
  end
  ```

- クラスを指定して補足する例外を限定する  
  `begin～rescue`を書くときに、例外のクラスを指定すると、例外オブジェクトのクラスが一致したときだけ例外を補足する。  
  ```ruby
  begin
    # 例外が起きうる処理
  rescue 補足したい例外クラス
    # 例外が発生したときの処理
  end
  ```
  1つの`rescue`節に複数の例外クラスを指定することもできる。  
  例外オブジェクトを変数に格納することもできる。  

- 例外クラスの継承関係を理解する  
  すべての例外クラスはExceptionクラスを継承している。  
  その下に、多くの例外クラスがサブクラスとしてぶら下がっている。  
  StandardErrorクラスは通常のプログラムで発生する可能性の高い例外クラスを表すクラス。  
  NoMemoryErrorクラスやSystemExitクラスはStandardErrorクラスを継承していないので、特殊なエラーが起きたことを表す。  
  `rescue`節に何もクラスを指定しなかったときはStandardErrorクラスが補足されるので、StandardErrorクラスを継承していない例外クラスは補足されない。  
  `rescue`節に例外クラスを指定した場合、補足されるのはそのクラス自身とそのサブクラスになる。  
  通常のプログラムで補足するのはStandardErrorクラスかそのサブクラスに限定するべきで、特別な理由がない限りはExceptionクラスやStandardErrorクラス以外のクラスを指定しないようにする。  
  