※スクール内timesの移植（2025/09/04）

- 学習時間：6h30min/27h/689h
- 学習内容：卒制

投稿機能に必要な各種モデルとActiveHashを使った疑似モデル、Activestorageの導入、投稿フォームの作成などをやっていました。  
当初の予定ではこの前にプロフィール機能を作ってユーザー画像の設定をできるようにするのでActive Storageは早めの導入にしていたけど、issueのレビューを受けてプロフィール機能を本リリースに回したので、このタイミングで導入しなくてよくなったのすっかり忘れて入れちゃった。  
予定が変わったらスケジュールもちゃんと見直して変更しようね。  
  
各種モデルを作ってマイグレーションファイルの編集もちゃんとしてマイグレーションして、ローカル更新してもエラー出ないから大丈夫だな～～～と思ってプッシュしたら本番環境で503エラーが出ちゃいました。  
当初は自動デプロイもエラーなくちゃんとできてるのになぜ！？と思ったのですが、ふたを開けてみればモデルファイルで`belongs_to`と書くべきところを`belong_to`にしていたのが原因でした。  
本番環境のログで当初目についたのが`[info] WARN could not unmount /rootfs: EINVAL: Invalid argument`だったのですが、これは無視していい奴だそうです。  
ログでerrorの表記を探して見つけたのが以下のエラーでした。  
```
nrt [error] [PC01] instance refused connection. is your app listening on 0.0.0.0:3000? make sure it is not only listening on 127.0.0.1 (hint: look at your startup logs, servers often print the address they are listening on)

nrt [error] [PR01] no known healthy instances found for route tcp/443. (hint: is your app shut down? is there an ongoing deployment with a volume or are you using the 'immediate' strategy? have your app's instances all reached their hard limit?)

nrt [error] [PR01] no known healthy instances found for route tcp/443. (hint: is your app shut down? is there an ongoing deployment with a volume or are you using the 'immediate' strategy? have your app's instances all reached their hard limit?)
nrt [error] [PR01] no known healthy instances found for route tcp/443. (hint: is your app shut down? is there an ongoing deployment with a volume or are you using the 'immediate' strategy? have your app's instances all reached their hard limit?)
```
DeepL翻訳にかけると
```
nrt [error] [PC01] instance refused connection.アプリケーションが0.0.0.0:3000をリッスンしていませんか？127.0.0.1だけをリッスンしていないか確認してください（ヒント：起動ログを見てください、サーバーはしばしばリッスンしているアドレスを表示します）。

nrt [error] [PR01] route tcp/443 の既知の健全なインスタンスが見つかりません。(ヒント: アプリがシャットダウンされているか、ボリュームで継続中のデプロイがあるか、「即時」戦略を使用しているか、アプリのインスタンスがすべてハードリミットに達しているか)

nrt [error] [PR01] ルートtcp/443の既知の健全なインスタンスが見つかりません。(ヒント: アプリがシャットダウンされているか、ボリュームでデプロイが進行中か、「即時」戦略を使用しているか、アプリのインスタンスがすべてハードリミットに達しているか)
nrt [error] [PR01] ルートtcp/443の既知の健全なインスタンスが見つかりません。(ヒント: アプリはシャットダウンしていますか。ボリュームを使用したデプロイが進行中ですか。それとも「即時」戦略を使用していますか。アプリのインスタンスはすべてハードリミットに達していますか。)
```
という感じで、どういうことだ～～～？？？と、とりあえず一番最初の`instance refused connection. is your app listening on 0.0.0.0:3000?`で検索をかけたら、公式コミュニティの質問がひっかかってくれました。  
[\[error\]instance refused connection.](https://community.fly.io/t/error-instance-refused-connection/13013)  
> Pretty much all that is saying is that your server didn’t start, and to [look at your log files](https://fly.io/docs/rails/getting-started/existing/#view-log-files) to see why.
> 
> （翻訳）つまり、サーバーが起動しなかったので、ログファイルを見て原因を調べろ、ということだ。

もう一回ログ（今度はBooting Pumaのあたり）を見直したら、
```
nrt [info] /usr/local/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `belong_to' for class Review (NoMethodError)
nrt [info] Did you mean? belongs_
```
お前だーーー！！！  
ということでモデルファイルの記述を修正して再度デプロイしたら直りました…。  
この手のエラーはサーバー再起動しないとわからないので、コントローラとかモデルファイルとかいじったら念のため`docker compose restart`する癖付けといたほうがいいかな…誤字を自分で見つけられないタイプなので…。  
誤字探すのだけAIに任せたい。だめですか？
